# Generated by Django 5.1.4 on 2025-04-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestContactModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("consulta", "Consulta general"),
                            ("presupuesto", "Solicitud de presupuesto"),
                            ("colaboracion", "Propuesta de colaboración"),
                            ("laboral", "Oportunidad laboral"),
                            ("otro", "Otro motivo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "servicio",
                    models.CharField(
                        choices=[
                            ("automatizacion", "Automatizaciones"),
                            ("ciencia", "Ciencia de Datos"),
                            ("backend", "Desarrollo Backend"),
                            ("analisis", "Análisis de Datos"),
                            ("ingenieria", "Ingeniería de Datos"),
                        ],
                        max_length=20,
                    ),
                ),
                ("mensaje", models.TextField(blank=True)),
                ("latitud", models.FloatField(blank=True, null=True)),
                ("longitud", models.FloatField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contacto",
                "verbose_name_plural": "Contactos",
                "ordering": ["-creado_en"],
            },
        ),
    ]
