# Generated by Django 5.1.4 on 2025-04-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReseniaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("posicion", models.CharField(max_length=100)),
                ("empresa", models.CharField(max_length=255)),
                (
                    "servicio",
                    models.CharField(
                        choices=[
                            ("automatizacion", "Automatizaciones"),
                            ("ciencia", "Ciencia de Datos"),
                            ("backend", "Desarrollo Backend"),
                            ("analisis", "Análisis de Datos"),
                            ("ingenieria", "Ingeniería de Datos"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resenia", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "calificacion",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "★☆☆☆☆"),
                            (2, "★★☆☆☆"),
                            (3, "★★★☆☆"),
                            (4, "★★★★☆"),
                            (5, "★★★★★"),
                        ],
                        default=5,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reseña",
                "verbose_name_plural": "Reseña",
                "ordering": ["-creado_en"],
            },
        ),
    ]
