# Generated by Django 5.1.4 on 2025-04-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0003_githubrepo"),
    ]

    operations = [
        migrations.AddField(
            model_name="reseniamodel",
            name="linkedin",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="reseniamodel",
            name="servicio",
            field=models.CharField(
                choices=[
                    ("automatizacion", "Automatizaciones"),
                    ("ciencia", "Ciencia de Datos"),
                    ("backend", "Desarrollo Backend"),
                    ("analisis", "Análisis de Datos"),
                    ("ingenieria", "Ingeniería de Datos"),
                    ("trabajo", "Trabajamos juntos"),
                ],
                max_length=20,
            ),
        ),
    ]
