# Generated by Django 5.1.4 on 2025-04-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0005_certificacionesmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrasesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("autor", models.CharField(max_length=255)),
                ("frase", models.TextField()),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Frase",
                "verbose_name_plural": "Frase",
                "ordering": ["-creado_en", "autor"],
            },
        ),
    ]
