# Generated by Django 5.1.4 on 2025-04-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0006_frasesmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora en que se recibió la petición",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP de quien hace la petición"
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Ruta solicitada (request.path)", max_length=2000
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        help_text="Método HTTP (GET, POST, …)", max_length=10
                    ),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        help_text="Código de respuesta HTTP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(help_text="Encabezado User-Agent completo"),
                ),
                (
                    "referer",
                    models.URLField(
                        blank=True,
                        help_text="Página origen (Referer header), si existe",
                        null=True,
                    ),
                ),
                (
                    "accept_language",
                    models.CharField(
                        blank=True,
                        help_text="Idiomas preferidos (Accept-Language header)",
                        max_length=255,
                    ),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Tiempo de respuesta en milisegundos (opcional)",
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="País aproximado (usando GeoIP, opcional)",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Visita de página",
                "verbose_name_plural": "Visitas de página",
                "ordering": ["-timestamp"],
            },
        ),
    ]
